'use client';

import jsPDF from 'jspdf';
import { Persona } from '@/types/pitch';

const MIDNIGHT = '#1A1E2E';
const TEAL = '#2DD4BF';
const SLATE = '#64748B';
const PAGE_W = 210;
const MARGIN = 14;
const CONTENT_W = PAGE_W - MARGIN * 2;

function addPageHeader(doc: jsPDF, pitchId?: string) {
  doc.setFillColor(MIDNIGHT);
  doc.rect(0, 0, PAGE_W, 22, 'F');
  doc.setTextColor('#F9FAFB');
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text('PitchLayer', MARGIN, 14);
  if (pitchId) {
    doc.setFontSize(8);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor('#94A3B8');
    doc.text(`Pitch ID: ${pitchId}`, PAGE_W - MARGIN, 14, { align: 'right' });
  }
}

function addSection(doc: jsPDF, label: string, value: string | string[], y: number): number {
  doc.setFontSize(9);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(TEAL);
  doc.text(label.toUpperCase(), MARGIN, y);
  y += 5;

  doc.setFont('helvetica', 'normal');
  doc.setTextColor(MIDNIGHT);
  doc.setFontSize(10);

  if (Array.isArray(value)) {
    for (const item of value) {
      const lines = doc.splitTextToSize(`• ${item}`, CONTENT_W);
      doc.text(lines, MARGIN + 2, y);
      y += lines.length * 5;
    }
  } else {
    const lines = doc.splitTextToSize(value, CONTENT_W);
    doc.text(lines, MARGIN, y);
    y += lines.length * 5;
  }

  return y + 4;
}

export default function PDFExport({ personas, pitchId }: { personas: Persona[]; pitchId?: string }) {
  const generate = () => {
    const doc = new jsPDF({ unit: 'mm', format: 'a4' });

    personas.forEach((persona, idx) => {
      if (idx > 0) doc.addPage();

      addPageHeader(doc, pitchId);

      // Persona name banner
      let y = 32;
      doc.setFontSize(16);
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(MIDNIGHT);
      doc.text(persona.name, MARGIN, y);
      y += 2;
      doc.setDrawColor(TEAL);
      doc.setLineWidth(0.5);
      doc.line(MARGIN, y, PAGE_W - MARGIN, y);
      y += 8;

      y = addSection(doc, 'Summary', persona.summary, y);
      y = addSection(doc, 'Challenge', persona.challenge, y);
      y = addSection(doc, 'Value Proposition', persona.value_prop, y);

      if (persona.benefits?.length) {
        y = addSection(doc, 'Benefits', persona.benefits, y);
      }
      if (persona.headlines?.length) {
        y = addSection(doc, 'Headlines', persona.headlines, y);
      }
      if (persona.talking_points?.length) {
        y = addSection(doc, 'Talking Points', persona.talking_points, y);
      }
      if (persona.cta) {
        // CTA highlight box
        doc.setFillColor('#F0FDFA');
        doc.roundedRect(MARGIN, y, CONTENT_W, 14, 2, 2, 'F');
        doc.setFontSize(9);
        doc.setFont('helvetica', 'bold');
        doc.setTextColor(TEAL);
        doc.text('CALL TO ACTION', MARGIN + 3, y + 5);
        doc.setFont('helvetica', 'normal');
        doc.setTextColor(MIDNIGHT);
        doc.setFontSize(10);
        const ctaLines = doc.splitTextToSize(persona.cta, CONTENT_W - 6);
        doc.text(ctaLines, MARGIN + 3, y + 10);
        y += 18;
      }

      // Footer
      doc.setFontSize(8);
      doc.setTextColor(SLATE);
      doc.text(`Page ${idx + 1} of ${personas.length}`, PAGE_W - MARGIN, 290, { align: 'right' });
      doc.text('Generated by PitchLayer', MARGIN, 290);
    });

    doc.save(`pitch-${pitchId || 'export'}.pdf`);
  };

  return (
    <button onClick={generate} className="btn bg-teal text-midnight hover:bg-teal/80">
      Export PDF
    </button>
  );
}
